include ../../global_config

OBJS = ../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/timestretch.o

OUTPUT = ../$(OBJDIR)/timestretch.plugin

include ../../plugin_config




$(OBJDIR)/timestretch.o: timestretch.C
