#DV_DIR := $(shell expr libdv-0.9.5 )
LIBRAW_DIR := $(shell expr libraw-0.9.0 )

LIBRAW_OBJS := \
	$(OBJDIR)/libraw1394/src/errors.o \
	$(OBJDIR)/libraw1394/src/eventloop.o \
	$(OBJDIR)/libraw1394/src/fcp.o \
	$(OBJDIR)/libraw1394/src/iso.o \
	$(OBJDIR)/libraw1394/src/main.o \
	$(OBJDIR)/libraw1394/src/readwrite.o


LIBRAW_CFLAGS += -Ilibraw1394/src


DIRS += $(OBJDIR)/libraw1394/src


