#!/bin/sh
VERSION=1.0.0

# Be sure to put exit statements in the beginning of
# /usr/lib/rpm/brp-strip 
# /usr/lib/rpm/brp-strip-comment-note 
# /usr/lib/rpm/brp-strip-shared
# so they don't strip the theme plugins

DEST=/usr/src/redhat
NAME=hvirtual-$VERSION

# CLEAN SOURCE DIRECTORIES
make clean

# CREATE DIRECTORIES
rm -r $DEST/$NAME
mkdir $DEST/$NAME

# COPY SOURCE FILES
cp -a * $DEST/$NAME
#echo 'USE_STATIC=y' > $DEST/$NAME/global_config
#cat global_config >> $DEST/$NAME/global_config

# MAKE TARBALL

cd $DEST/
chmod -R u+w $NAME


tar jcf SOURCES/$NAME-src.tar.bz2 $NAME





# MAKE SPEC FILE
cat > $NAME-1.spec << EOF

Summary: Complete production environment for audio and video.
Name: hvirtual
Version: $VERSION
Release: 1
Copyright: GPL
Group: Applications/Video
Source: http://prdownloads.sourceforge.net/heroines/hvirtual-$VERSION-src.tar.bz2
BuildRoot: /var/tmp/%{name}-buildroot
Provides: Everything
Prefix: /usr

%description

It's about transforming the impossible into reality.

%prep
%setup -q
%build
make

%install
mkdir -p /var/tmp/%{name}-buildroot/usr/lib/cinelerra
mkdir -p /var/tmp/%{name}-buildroot/usr/bin
strip cinelerra/i686/cinelerra
cp cinelerra/i686/cinelerra /var/tmp/%{name}-buildroot/usr/bin
cp plugins/i686/* /var/tmp/%{name}-buildroot/usr/lib/cinelerra

strip libmpeg3/i686/mpeg3toc
strip libmpeg3/i686/mpeg3cat
strip libmpeg3/i686/mpeg3dump
cp libmpeg3/i686/mpeg3toc /var/tmp/%{name}-buildroot/usr/bin
cp libmpeg3/i686/mpeg3cat /var/tmp/%{name}-buildroot/usr/bin
cp libmpeg3/i686/mpeg3dump /var/tmp/%{name}-buildroot/usr/bin

strip xmovie/i686/xmovie
cp xmovie/i686/xmovie /var/tmp/%{name}-buildroot/usr/bin/

strip mix/i686/mix2000
cp mix/i686/mix2000 /var/tmp/%{name}-buildroot/usr/bin/

strip mplexhi/i686/mplexhi
cp mplexhi/i686/mplexhi /var/tmp/%{name}-buildroot/usr/bin/

strip mplexlo/i686/mplexlo
cp mplexlo/i686/mplexlo /var/tmp/%{name}-buildroot/usr/bin/

%clean
rm -rf /var/tmp/%{name}-buildroot

%files
%defattr(-,root,root)

/usr/bin/cinelerra
/usr/lib/cinelerra
/usr/bin/mpeg3toc
/usr/bin/mpeg3cat
/usr/bin/mpeg3dump
/usr/bin/xmovie
/usr/bin/mix2000
/usr/bin/mplexhi
/usr/bin/mplexlo

EOF
