/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define HAVE_MMX 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_AC3 1
#define CONFIG_MPGLIB 1
#define CONFIG_GRAB 1
