# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
CC=gcc
AR=ar
OPTFLAGS=-O3 -march=i686 -fmessage-length=0 -funroll-all-loops -fomit-frame-pointer -malign-loops=2 -malign-jumps=2 -malign-functions=2 -I/usr/local/include
TARGET_ARCH_X86=yes
TARGET_MMX=yes
CONFIG_ENCODERS=yes
CONFIG_DECODERS=yes
CONFIG_AC3=yes
CONFIG_MPGLIB=yes
CONFIG_GRAB=yes
