IMAGES = \
	../plugins/defaulttheme/data/arrow.png \
	../plugins/defaulttheme/data/cut.png \
	../plugins/defaulttheme/data/ibeam.png \
	../plugins/defaulttheme/data/paste.png


all:
	cp $(IMAGES) .
	makeinfo --html --no-split cinelerra.texi
