/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define HAVE_MMX 1
#define HAVE_STRPTIME 1
#define HAVE_LRINTF 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_AC3 1
#define CONFIG_MPEGAUDIO_HP 1
#define CONFIG_VIDEO4LINUX 1
#define CONFIG_AUDIO_OSS 1
#define CONFIG_NETWORK 1
#define CONFIG_ZLIB 1
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1
#define restrict __restrict__
