include ../../global_config

OBJS = ../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/denoisefft.o

OUTPUT = $(PLUGIN_DIR)/denoisefft.plugin

include ../../plugin_config


$(OBJDIR)/denoisefft.o: denoisefft.C
