include ../../global_config

OBJS = ../colors/$(OBJDIR)/plugincolors.o \
	$(OBJDIR)/huesaturation.o

OUTPUT = $(PLUGIN_DIR)/huesaturation.plugin

include ../../plugin_config


$(OBJDIR)/huesaturation.o: huesaturation.C
