include ../../global_config

OBJS = \
	../colors/$(OBJDIR)/plugincolors.o \
	../parametric/$(OBJDIR)/fourier.o \
	$(OBJDIR)/spectrogram.o

OUTPUT = $(PLUGIN_DIR)/spectrogram.plugin

include ../../plugin_config




$(OBJDIR)/spectrogram.o: spectrogram.C
